### ISSUE TITLE
Le bouton "Nouvelle journée" ne s'affiche que lorsque l'événement est validé

### ISSUE THREAD

**Issue by mpellegrin** [Darkjeff/Event#10]
Du coup, l'option "valider toutes les journées" qui s'affiche en même temps que la validation de l'événement, ne sert à rien, et il faut valider toutes les journées une par une.

![image](https://user-images.githubusercontent.com/3110368/62799659-afb82680-bae1-11e9-9051-90da5e65e2a0.png)
![image](https://user-images.githubusercontent.com/3110368/62799663-b21a8080-bae1-11e9-869c-c02dc6f0c0dc.png)
![image](https://user-images.githubusercontent.com/3110368/62799664-b5157100-bae1-11e9-9ed6-47237e5c1c48.png)

**Comment by tlse-vins** [comment]
""Du coup, l'option "valider toutes les journées" qui s'affiche en même temps que la validation de l'événement, ne sert à rien, et il faut valider toutes les journées une par une.""
Effectivement il ne sert à rien mais dans ma version les journée sont bien validés dans un cas comme dans l'autre.

Le bouton "nouvelle journée" est bien dans ta dernière capture.
Dans ma version lors de la validation de l’événement une journée se créer de la date se l'événement.
Tu devrais avoir dans ta dernière capture écran une journée du 09/08/2019

**Comment by mpellegrin** [comment]
> Le bouton "nouvelle journée" est bien dans ta dernière capture.
Oui, mais après validation, je ne peux pas créer des journées, puis valider l'événement et toutes les journées en même temps.

> Dans ma version lors de la validation de l’événement une journée se créer de la date se l'événement.
> Tu devrais avoir dans ta dernière capture écran une journée du 09/08/2019
On parle bien de la même version, celle qui se trouve dans le dépôt sur la branche master ? Ce n'est pas une version différente qui se trouverait en production de votre côté ?

**Comment by tlse-vins** [comment]
Pour ma part, je crée l'événement 
ex: "Cours 2019" une date de début mais pas de date de fin.
une journée se crée lors de la validation par rapport à la date de création de l'événement que je peux modifier. Elle est déjà validé.
Je crée par la suite d'autre journée que je valide les une après les autres.

La version qui se trouve sur ce dépôt est la mienne, hormis les dernières modifications apportés.

**Comment by mpellegrin** [comment]
Mon événement n'est pas validé automatiquement, d'où le fait que je ne vois pas le bouton sur l'événement en brouillon. Le bouton de création de journées indisponible pour les événements brouillon c'est clairement une règle de gestion actuelle : https://github.com/Darkjeff/Event/blob/a29ebbbea785c78d2a53a1549bf73a16ab81b459/htdocs/custom/event/fiche.php#L747

Je me posais donc la question de l'intérêt de valider toutes les journées en validant l'événement, si on ne peut pas créer de journées avant de valider l'événement.

À noter que mon paramétrage actuel est : 
![image](https://user-images.githubusercontent.com/3110368/62809282-c6b74280-bafa-11e9-9c79-42a07be67a33.png)

Je ne sais pas encore pourquoi la journée par défaut ne se crée pas chez moi, par contre.

**Comment by tlse-vins** [comment]
Oui c'est vraiment en 2 étapes on valide d'abord l'événement. Oui par la suite les journées. 
Mais oui à journée active par défaut à la création. 
Version php 5.6.33
Fait ce que tu penses le plus juste.
J'attend que ma V10 soit en place avec la dernière version du PHP afin de faire les tests.

**Comment by tlse-vins** [comment]
Est ce que tu as pu faire fonctionner le module?
J'ai une V10 avec le module, la version PHP est 5.6.38.
Dolibarr et le module auront du mal à tourner avec une version de PHP de 7.
Je te suggère de baisser ta version de PHP.
