### ISSUE TITLE
Impossible de créer une invitation manuelle

### ISSUE THREAD

**Issue by mpellegrin** [Darkjeff/Event#11]
Scénario :

 - Dolibarr 7.0.5
 - Création d'un événement à deux journées, inscription par journée désactivée
 - Clic sur une journée, puis "inscription manuelle"
 - Au moment de choisir l'utilisateur, redirection vers une page blanche (sans avoir cliqué "valider")

En creusant dans le formulaire, j'ai constaté qu'un formulaire étaient imbriqué dans le premier au niveau du choix de journée : 
![image](https://user-images.githubusercontent.com/3110368/62799341-d9bd1900-bae0-11e9-8bac-ab56ff685451.png)

 - D'où la validation automatique à la sélection de l'utilisateur
 - Et d'où la page blanche, le formulaire de sélection du jour ajoute toutes les en-têtes du formulaire, avec `action="set"` ; cette action n'est pas valable pour ce formulaire qui n'accepte que `"add"` ou `"addd"`.

La fonction qui est responsable de cette apparition du sous-formulaire est `select_day` dans le fichier `lib/html.formregistration.class.php`.

Je ne sais pas si ce comportement est normal ou comment le corriger sans créer d'effets de bord sur les autres formuaires (si cette fonction est réutilisée ailleurs).

**Comment by tlse-vins** [comment]
Je suis en 7.0.4 et cela fonction parfaitement.
il y a eu des modifications précédemment , est ce que ça ne vient pas de là?

Si tu veux que je t'explique en détail tout le fonctionnement du module contact moi par mail à: vincent.paraud AT gmail.com

**Comment by mpellegrin** [comment]
Je viens de tester avec la version master, avant mes modifications, le comportement est identique.

Je ne comprends pas ce que ce formulaire vient faire imbriqué dans l'autre, et si je retire ces trois lignes présentes dans select_day, ça fonctionne parfaitement (y compris l'appel ajax pour récupérer les informations du contact sélectionné) : 
```
    	$out.= '<form method="POST" action="'.$_SERVER['PHP_SELF'].'" name="form">';
    	$out.= '<input type="hidden" name="action" value="set">';
    	$out.= '<input type="hidden" name="token" value="'.$_SESSION['newtoken'].'">';
```

**Comment by tlse-vins** [comment]
Salut, 

Est ce que tu avais une page blanche lorsque tu voulais créer une invitation?
Car c'est ce que j'ai pour l'instant.

**Comment by tlse-vins** [comment]
J'ai trouvé ça mais je ne sais pas si ça a un rapport.
https://github.com/Dolibarr/dolibarr/issues/3585

**Comment by tlse-vins** [comment]
Résolue.
